{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "stock_ = 'TATASTEEL'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "from nsepy import get_history as gh\n",
    "import datetime as dt\n",
    "from matplotlib import pyplot as plt\n",
    "from sklearn import model_selection\n",
    "from sklearn.metrics import confusion_matrix\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.model_selection import train_test_split\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from sklearn.preprocessing import MinMaxScaler\n",
    "import keras\n",
    "from keras.models import Sequential\n",
    "from keras.layers import Dense\n",
    "from keras.layers import LSTM\n",
    "from keras.layers import Dropout"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_regressor(stk_data, start, end, lim):\n",
    "    stk_data['Date'] = stk_data.index\n",
    "    data2 = pd.DataFrame(columns = ['Date', 'Open', 'High', 'Low', 'Close'])\n",
    "    data2['Date'] = stk_data['Date']\n",
    "    data2['Open'] = stk_data['Open']\n",
    "    data2['High'] = stk_data['High']\n",
    "    data2['Low'] = stk_data['Low']\n",
    "    data2['Close'] = stk_data['Close']\n",
    "    \n",
    "    train_set = data2.iloc[:, 1:2].values\n",
    "    sc = MinMaxScaler(feature_range = (0, 1))\n",
    "    training_set_scaled = sc.fit_transform(train_set)\n",
    "    X_train = []\n",
    "    y_train = []\n",
    "    for i in range(60, lim):\n",
    "        X_train.append(training_set_scaled[i-60:i, 0])\n",
    "        y_train.append(training_set_scaled[i, 0]) \n",
    "    X_train, y_train = np.array(X_train), np.array(y_train)\n",
    "    X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))\n",
    "    \n",
    "    regressor = Sequential()\n",
    "    regressor.add(LSTM(units = 50, return_sequences = True, input_shape = (X_train.shape[1], 1)))\n",
    "    regressor.add(Dropout(0.2))\n",
    "    regressor.add(LSTM(units = 50, return_sequences = True))\n",
    "    regressor.add(Dropout(0.2))\n",
    "    regressor.add(LSTM(units = 50, return_sequences = True))\n",
    "    regressor.add(Dropout(0.2))\n",
    "    regressor.add(LSTM(units = 50))\n",
    "    regressor.add(Dropout(0.2))\n",
    "    regressor.add(Dense(units = 1))\n",
    "    \n",
    "    regressor.compile(optimizer = 'adam', loss = 'mean_squared_error')\n",
    "    regressor.fit(X_train, y_train, epochs = 15, batch_size = 32, validation_split=0.2)\n",
    "    \n",
    "    return regressor"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "unexpected EOF while parsing (<ipython-input-31-637dae9458e4>, line 1)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;36m  File \u001b[1;32m\"<ipython-input-31-637dae9458e4>\"\u001b[1;36m, line \u001b[1;32m1\u001b[0m\n\u001b[1;33m    def comparison():\u001b[0m\n\u001b[1;37m                     ^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m unexpected EOF while parsing\n"
     ]
    }
   ],
   "source": [
    "def comparison(start, end, lim, regressor, heading):\n",
    "    testdataframe= gh(symbol=stock_,start=dt.datetime(2020,1,1),end=dt.datetime(2020,8,31))\n",
    "    testdataframe['Date'] = testdataframe.index\n",
    "    testdata = pd.DataFrame(columns = ['Date', 'Open', 'High', 'Low', 'Close'])\n",
    "    testdata['Date'] = testdataframe['Date']\n",
    "    testdata['Open'] = testdataframe['Open']\n",
    "    testdata['High'] = testdataframe['High']\n",
    "    testdata['Low'] = testdataframe['Low']\n",
    "    testdata['Close'] = testdataframe['Close']\n",
    "    real_stock_price = testdata.iloc[:, 1:2].values\n",
    "    dataset_total = pd.concat((data2['Open'], testdata['Open']), axis = 0)\n",
    "    inputs = dataset_total[len(dataset_total) - len(testdata) - 60:].values\n",
    "    inputs = inputs.reshape(-1,1)\n",
    "    inputs = sc.transform(inputs)\n",
    "    X_test = []\n",
    "    #upper limit is number of days - 25\n",
    "    for i in range(60, lim):\n",
    "        print(i)\n",
    "        X_test.append(inputs[i-60:i, 0])\n",
    "    X_test = np.array(X_test)\n",
    "    X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))\n",
    "    predicted_stock_price = regressor.predict(X_test)\n",
    "    predicted_stock_price = sc.inverse_transform(predicted_stock_price)\n",
    "    plt.figure(figsize=(20,5))\n",
    "    print(heading)\n",
    "    plt.plot(real_stock_price, color = 'green', label = '{} Stock Price'.format(stock_))\n",
    "    plt.plot(predicted_stock_price, color = 'red', label = 'Predicted {} Stock Price'.format(stock_))\n",
    "    plt.title('{} Stock Price Prediction'.format(stock_))\n",
    "    plt.xlabel('Trading Day')\n",
    "    plt.ylabel('{} Stock Price'.format(stock_))\n",
    "    plt.legend()\n",
    "    plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Exception in thread Thread-702:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 670, in urlopen\n",
      "Exception in thread Thread-712:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 670, in urlopen\n",
      "Exception in thread Thread-716:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 670, in urlopen\n",
      "Exception in thread Thread-710:\n",
      "Thread-700Exception in thread Thread-714:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 670, in urlopen\n",
      "Exception in thread Thread-718:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 670, in urlopen\n",
      "Exception in thread Exception in thread Thread-706:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 670, in urlopen\n",
      "Exception in thread Thread-708:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 670, in urlopen\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 670, in urlopen\n",
      ":\n",
      "    httplib_response = self._make_request(\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 426, in _make_request\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 670, in urlopen\n",
      "    httplib_response = self._make_request(\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 426, in _make_request\n",
      "    httplib_response = self._make_request(    httplib_response = self._make_request(\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 426, in _make_request\n",
      "    Thread-704:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 670, in urlopen\n",
      "    httplib_response = self._make_request(\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 426, in _make_request\n",
      "    httplib_response = self._make_request(\n",
      "\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 426, in _make_request\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 426, in _make_request\n",
      "httplib_response = self._make_request(\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 426, in _make_request\n",
      "    httplib_response = self._make_request(        six.raise_from(e, None)\n",
      "  File \"<string>\", line 3, in raise_from\n",
      "httplib_response = self._make_request(\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 426, in _make_request\n",
      "\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 426, in _make_request\n",
      "    six.raise_from(e, None)            six.raise_from(e, None)\n",
      "  File \"<string>\", line 3, in raise_from\n",
      "    six.raise_from(e, None)\n",
      "    \n",
      "  File \"<string>\", line 3, in raise_from\n",
      "  File \"<string>\", line 3, in raise_from\n",
      "six.raise_from(e, None)\n",
      "  File \"<string>\", line 3, in raise_from\n",
      "six.raise_from(e, None)\n",
      "  File \"<string>\", line 3, in raise_from\n",
      "        six.raise_from(e, None)\n",
      "  File \"<string>\", line 3, in raise_from\n",
      "six.raise_from(e, None)httplib_response = self._make_request(\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 426, in _make_request\n",
      "\n",
      "  File \"<string>\", line 3, in raise_from\n",
      "    six.raise_from(e, None)    \n",
      "  File \"<string>\", line 3, in raise_from\n",
      "six.raise_from(e, None)\n",
      "  File \"<string>\", line 3, in raise_from\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 421, in _make_request\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 421, in _make_request\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 421, in _make_request\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 421, in _make_request\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 421, in _make_request\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 421, in _make_request\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 421, in _make_request\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 421, in _make_request\n",
      "    httplib_response = conn.getresponse()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 1347, in getresponse\n",
      "        httplib_response = conn.getresponse()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 1347, in getresponse\n",
      "httplib_response = conn.getresponse()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 1347, in getresponse\n",
      "    response.begin()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 307, in begin\n",
      "    httplib_response = conn.getresponse()  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 421, in _make_request\n",
      "    httplib_response = conn.getresponse()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 1347, in getresponse\n",
      "\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 1347, in getresponse\n",
      "    httplib_response = conn.getresponse()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 1347, in getresponse\n",
      "        httplib_response = conn.getresponse()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 1347, in getresponse\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 421, in _make_request\n",
      "    version, status, reason = self._read_status()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 268, in _read_status\n",
      "    httplib_response = conn.getresponse()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 1347, in getresponse\n",
      "    httplib_response = conn.getresponse()response.begin()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 307, in begin\n",
      "    response.begin()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 307, in begin\n",
      "    \n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 1347, in getresponse\n",
      "    response.begin()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 307, in begin\n",
      "response.begin()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 307, in begin\n",
      "    response.begin()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 307, in begin\n",
      "    httplib_response = conn.getresponse()\n",
      "        response.begin()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 307, in begin\n",
      "response.begin()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 307, in begin\n",
      "        version, status, reason = self._read_status()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 268, in _read_status\n",
      "    version, status, reason = self._read_status()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 268, in _read_status\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 1347, in getresponse\n",
      "    response.begin()version, status, reason = self._read_status()    version, status, reason = self._read_status()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 268, in _read_status\n",
      "    version, status, reason = self._read_status()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 268, in _read_status\n",
      "\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 307, in begin\n",
      "\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 268, in _read_status\n",
      "    version, status, reason = self._read_status()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 268, in _read_status\n",
      "        version, status, reason = self._read_status()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 268, in _read_status\n",
      "    response.begin()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 307, in begin\n",
      "    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\socket.py\", line 669, in readinto\n",
      "        line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\socket.py\", line 669, in readinto\n",
      "version, status, reason = self._read_status()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 268, in _read_status\n",
      "\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\socket.py\", line 669, in readinto\n",
      "    version, status, reason = self._read_status()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 268, in _read_status\n",
      "    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "        return self._sock.recv_into(b)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "    return self._sock.recv_into(b)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\socket.py\", line 669, in readinto\n",
      "    \n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\adapters.py\", line 439, in send\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\socket.py\", line 669, in readinto\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\adapters.py\", line 439, in send\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\socket.py\", line 669, in readinto\n",
      "line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\socket.py\", line 669, in readinto\n",
      "    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\socket.py\", line 669, in readinto\n",
      "    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\socket.py\", line 669, in readinto\n",
      "                return self._sock.recv_into(b)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\adapters.py\", line 439, in send\n",
      "return self._sock.recv_into(b)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\adapters.py\", line 439, in send\n",
      "return self._sock.recv_into(b)\n",
      "ConnectionResetError    resp = conn.urlopen(\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 726, in urlopen\n",
      "line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\socket.py\", line 669, in readinto\n",
      "    resp = conn.urlopen(\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 726, in urlopen\n",
      ": [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\adapters.py\", line 439, in send\n",
      "        return self._sock.recv_into(b)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "        return self._sock.recv_into(b)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\adapters.py\", line 439, in send\n",
      "    Traceback (most recent call last):\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\adapters.py\", line 439, in send\n",
      "        return self._sock.recv_into(b)\n",
      "resp = conn.urlopen(\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 726, in urlopen\n",
      "ConnectionResetError    : [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "resp = conn.urlopen(\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 726, in urlopen\n",
      "return self._sock.recv_into(b)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\adapters.py\", line 439, in send\n",
      "    retries = retries.increment(\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\util\\retry.py\", line 403, in increment\n",
      "return self._sock.recv_into(b)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\adapters.py\", line 439, in send\n",
      "resp = conn.urlopen(\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 726, in urlopen\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\adapters.py\", line 439, in send\n",
      "        resp = conn.urlopen(\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 726, in urlopen\n",
      "resp = conn.urlopen(\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 726, in urlopen\n",
      "    retries = retries.increment(\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\util\\retry.py\", line 403, in increment\n",
      "                resp = conn.urlopen(\n",
      "raise six.reraise(type(error), error, _stacktrace)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\packages\\six.py\", line 734, in reraise\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 726, in urlopen\n",
      "resp = conn.urlopen(retries = retries.increment(\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\util\\retry.py\", line 403, in increment\n",
      "\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 726, in urlopen\n",
      "    retries = retries.increment(\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\util\\retry.py\", line 403, in increment\n",
      "            resp = conn.urlopen(\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 726, in urlopen\n",
      "    retries = retries.increment(retries = retries.increment(\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\util\\retry.py\", line 403, in increment\n",
      "retries = retries.increment(\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\util\\retry.py\", line 403, in increment\n",
      "    raise value.with_traceback(tb)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 670, in urlopen\n",
      "        \n",
      "retries = retries.increment(raise six.reraise(type(error), error, _stacktrace)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\util\\retry.py\", line 403, in increment\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\util\\retry.py\", line 403, in increment\n",
      "\n",
      "                  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\packages\\six.py\", line 734, in reraise\n",
      "raise six.reraise(type(error), error, _stacktrace)retries = retries.increment(\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\util\\retry.py\", line 403, in increment\n",
      "raise six.reraise(type(error), error, _stacktrace)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\packages\\six.py\", line 734, in reraise\n",
      "raise six.reraise(type(error), error, _stacktrace)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\packages\\six.py\", line 734, in reraise\n",
      "\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\packages\\six.py\", line 734, in reraise\n",
      "            httplib_response = self._make_request(\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 426, in _make_request\n",
      "raise six.reraise(type(error), error, _stacktrace)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\packages\\six.py\", line 734, in reraise\n",
      "raise six.reraise(type(error), error, _stacktrace)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\packages\\six.py\", line 734, in reraise\n",
      "        raise six.reraise(type(error), error, _stacktrace)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\packages\\six.py\", line 734, in reraise\n",
      "retries = retries.increment(\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\util\\retry.py\", line 403, in increment\n",
      "    raise six.reraise(type(error), error, _stacktrace)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\packages\\six.py\", line 734, in reraise\n",
      "                raise value.with_traceback(tb)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 670, in urlopen\n",
      "    six.raise_from(e, None)\n",
      "  File \"<string>\", line 3, in raise_from\n",
      "raise value.with_traceback(tb)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 670, in urlopen\n",
      "raise value.with_traceback(tb)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 670, in urlopen\n",
      "raise value.with_traceback(tb)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 670, in urlopen\n",
      "    raise value.with_traceback(tb)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 670, in urlopen\n",
      "    raise value.with_traceback(tb)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 670, in urlopen\n",
      "            raise six.reraise(type(error), error, _stacktrace)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\packages\\six.py\", line 734, in reraise\n",
      "raise value.with_traceback(tb)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 670, in urlopen\n",
      "raise value.with_traceback(tb)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 670, in urlopen\n",
      "    httplib_response = self._make_request(\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 426, in _make_request\n",
      "            httplib_response = self._make_request(\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 426, in _make_request\n",
      "httplib_response = self._make_request(\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 426, in _make_request\n",
      "httplib_response = self._make_request(\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 426, in _make_request\n",
      "    httplib_response = self._make_request(    httplib_response = self._make_request(\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 426, in _make_request\n",
      "        raise value.with_traceback(tb)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 670, in urlopen\n",
      "httplib_response = self._make_request(\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 426, in _make_request\n",
      "\n",
      "        six.raise_from(e, None)\n",
      "  File \"<string>\", line 3, in raise_from\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 426, in _make_request\n",
      "six.raise_from(e, None)\n",
      "  File \"<string>\", line 3, in raise_from\n",
      "    httplib_response = self._make_request(\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 426, in _make_request\n",
      "    six.raise_from(e, None)\n",
      "  File \"<string>\", line 3, in raise_from\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 421, in _make_request\n",
      "    six.raise_from(e, None)    six.raise_from(e, None)\n",
      "          File \"<string>\", line 3, in raise_from\n",
      "six.raise_from(e, None)\n",
      "  File \"<string>\", line 3, in raise_from\n",
      "    \n",
      "six.raise_from(e, None)\n",
      "  File \"<string>\", line 3, in raise_from\n",
      "  File \"<string>\", line 3, in raise_from\n",
      "    httplib_response = self._make_request(six.raise_from(e, None)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 426, in _make_request\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 421, in _make_request\n",
      "\n",
      "  File \"<string>\", line 3, in raise_from\n",
      "    httplib_response = conn.getresponse()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 1347, in getresponse\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 421, in _make_request\n",
      "    httplib_response = conn.getresponse()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 1347, in getresponse\n",
      "      File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 421, in _make_request\n",
      "six.raise_from(e, None)\n",
      "  File \"<string>\", line 3, in raise_from\n",
      "      File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 421, in _make_request\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 421, in _make_request\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 421, in _make_request\n",
      "httplib_response = conn.getresponse()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 1347, in getresponse\n",
      "          File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 421, in _make_request\n",
      "response.begin()httplib_response = conn.getresponse()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 1347, in getresponse\n",
      "\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 307, in begin\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 421, in _make_request\n",
      "    httplib_response = conn.getresponse()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 1347, in getresponse\n",
      "        httplib_response = conn.getresponse()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 1347, in getresponse\n",
      "    httplib_response = conn.getresponse()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 1347, in getresponse\n",
      "    response.begin()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 307, in begin\n",
      "httplib_response = conn.getresponse()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 1347, in getresponse\n",
      "    version, status, reason = self._read_status()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 268, in _read_status\n",
      "        response.begin()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 307, in begin\n",
      "httplib_response = conn.getresponse()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 1347, in getresponse\n",
      "      File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 421, in _make_request\n",
      "version, status, reason = self._read_status()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 268, in _read_status\n",
      "    response.begin()    \n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 307, in begin\n",
      "line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\socket.py\", line 669, in readinto\n",
      "            response.begin()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 307, in begin\n",
      "version, status, reason = self._read_status()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 268, in _read_status\n",
      "response.begin()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 307, in begin\n",
      "        response.begin()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 307, in begin\n",
      "response.begin()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 307, in begin\n",
      "            version, status, reason = self._read_status()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 268, in _read_status\n",
      "response.begin()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 307, in begin\n",
      "line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\socket.py\", line 669, in readinto\n",
      "    version, status, reason = self._read_status()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 268, in _read_status\n",
      "                version, status, reason = self._read_status()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 268, in _read_status\n",
      "        version, status, reason = self._read_status()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 268, in _read_status\n",
      "version, status, reason = self._read_status()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 268, in _read_status\n",
      "httplib_response = conn.getresponse()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 1347, in getresponse\n",
      "return self._sock.recv_into(b)line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\socket.py\", line 669, in readinto\n",
      "        \n",
      "urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n",
      "    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\socket.py\", line 669, in readinto\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\socket.py\", line 669, in readinto\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\threading.py\", line 932, in _bootstrap_inner\n",
      "        version, status, reason = self._read_status()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 268, in _read_status\n",
      "line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\socket.py\", line 669, in readinto\n",
      "    return self._sock.recv_into(b)\n",
      "urllib3.exceptions.ProtocolError    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\socket.py\", line 669, in readinto\n",
      "\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\socket.py\", line 669, in readinto\n",
      ": ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\threading.py\", line 932, in _bootstrap_inner\n",
      "        return self._sock.recv_into(b)\n",
      "urllib3.exceptions.ProtocolErrorreturn self._sock.recv_into(b)\n",
      "urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\threading.py\", line 932, in _bootstrap_inner\n",
      ":         ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "    self.run()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\commons.py\", line 132, in run\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\threading.py\", line 932, in _bootstrap_inner\n",
      "return self._sock.recv_into(b)\n",
      "urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\threading.py\", line 932, in _bootstrap_inner\n",
      "line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\socket.py\", line 669, in readinto\n",
      "        response.begin()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 307, in begin\n",
      "return self._sock.recv_into(b)\n",
      "urllib3.exceptions.    ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\threading.py\", line 932, in _bootstrap_inner\n",
      "return self._sock.recv_into(b)\n",
      "urllib3.exceptions.ProtocolError        self.result = self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\history.py\", line 138, in get_history\n",
      "return self._sock.recv_into(b)\n",
      "urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\threading.py\", line 932, in _bootstrap_inner\n",
      ": ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\commons.py\", line 132, in run\n",
      "    version, status, reason = self._read_status()\n",
      "      File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 268, in _read_status\n",
      "return self._sock.recv_into(b)\n",
      "urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()        \n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\commons.py\", line 132, in run\n",
      "self.run()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\commons.py\", line 132, in run\n",
      "return get_history_quanta(**kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\history.py\", line 143, in get_history_quanta\n",
      "    self.run()        \n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\commons.py\", line 132, in run\n",
      "line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")self.result = self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\history.py\", line 138, in get_history\n",
      "\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\socket.py\", line 669, in readinto\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\history.py\", line 138, in get_history\n",
      "            self.result = self._target(*self._args, **self._kwargs)self.run()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\commons.py\", line 132, in run\n",
      "    \n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\history.py\", line 138, in get_history\n",
      "    return get_history_quanta(**kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\history.py\", line 143, in get_history_quanta\n",
      "self.run()self.run()        \n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\commons.py\", line 132, in run\n",
      "\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\commons.py\", line 132, in run\n",
      "self.result = self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\history.py\", line 138, in get_history\n",
      "return get_history_quanta(**kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\history.py\", line 143, in get_history_quanta\n",
      "            df = url_to_df(url=url,\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\history.py\", line 151, in url_to_df\n",
      "return get_history_quanta(**kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\history.py\", line 143, in get_history_quanta\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "            self.result = self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\history.py\", line 138, in get_history\n",
      "return self._sock.recv_into(b)df = url_to_df(url=url,\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\history.py\", line 151, in url_to_df\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\history.py\", line 138, in get_history\n",
      "        \n",
      "urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\threading.py\", line 932, in _bootstrap_inner\n",
      "self.run()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\commons.py\", line 132, in run\n",
      "    self.result = self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\history.py\", line 138, in get_history\n",
      "    resp = url(**params)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\commons.py\", line 167, in __call__\n",
      "df = url_to_df(url=url,\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\history.py\", line 151, in url_to_df\n",
      "return get_history_quanta(**kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\history.py\", line 143, in get_history_quanta\n",
      "    return get_history_quanta(**kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\history.py\", line 143, in get_history_quanta\n",
      "    return self.session.get(url, params=kwargs, proxies = self.proxy )\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\sessions.py\", line 543, in get\n",
      "    resp = url(**params)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\commons.py\", line 167, in __call__\n",
      "            df = url_to_df(url=url,\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\history.py\", line 151, in url_to_df\n",
      "return get_history_quanta(**kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\history.py\", line 143, in get_history_quanta\n",
      "    return self.request('GET', url, **kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\sessions.py\", line 530, in request\n",
      "            return get_history_quanta(**kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\history.py\", line 143, in get_history_quanta\n",
      "self.result = self._target(*self._args, **self._kwargs)            df = url_to_df(url=url,\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\history.py\", line 151, in url_to_df\n",
      "self.run()\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\commons.py\", line 132, in run\n",
      "resp = url(**params)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\commons.py\", line 167, in __call__\n",
      "\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\history.py\", line 138, in get_history\n",
      "df = url_to_df(url=url,\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\history.py\", line 151, in url_to_df\n",
      "df = url_to_df(url=url,\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\history.py\", line 151, in url_to_df\n",
      "    resp = url(**params)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\commons.py\", line 167, in __call__\n",
      "        resp = url(**params)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\commons.py\", line 167, in __call__\n",
      "    return get_history_quanta(**kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\history.py\", line 143, in get_history_quanta\n",
      "return self.session.get(url, params=kwargs, proxies = self.proxy )\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\sessions.py\", line 543, in get\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\sessions.py\", line 643, in send\n",
      "    df = url_to_df(url=url,\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\history.py\", line 151, in url_to_df\n",
      "            resp = url(**params)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\commons.py\", line 167, in __call__\n",
      "    return self.request('GET', url, **kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\sessions.py\", line 530, in request\n",
      "return self.session.get(url, params=kwargs, proxies = self.proxy )\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\sessions.py\", line 543, in get\n",
      "    return self.session.get(url, params=kwargs, proxies = self.proxy )\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\sessions.py\", line 543, in get\n",
      "self.result = self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\history.py\", line 138, in get_history\n",
      "    return self.session.get(url, params=kwargs, proxies = self.proxy )\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\sessions.py\", line 543, in get\n",
      "        resp = url(**params)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\commons.py\", line 167, in __call__\n",
      "        return self.request('GET', url, **kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\sessions.py\", line 530, in request\n",
      "    resp = url(**params)return self.session.get(url, params=kwargs, proxies = self.proxy )\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\commons.py\", line 167, in __call__\n",
      "    df = url_to_df(url=url,\n",
      "    r = adapter.send(request, **kwargs)      File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\sessions.py\", line 543, in get\n",
      "    return get_history_quanta(**kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\history.py\", line 143, in get_history_quanta\n",
      "\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\history.py\", line 151, in url_to_df\n",
      "    return self.request('GET', url, **kwargs)    return self.request('GET', url, **kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\sessions.py\", line 530, in request\n",
      "return self.session.get(url, params=kwargs, proxies = self.proxy )\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\sessions.py\", line 530, in request\n",
      "    resp = self.send(prep, **send_kwargs)    resp = url(**params)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\commons.py\", line 167, in __call__\n",
      "\n",
      "    return self.session.get(url, params=kwargs, proxies = self.proxy )\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\sessions.py\", line 543, in get\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\adapters.py\", line 498, in send\n",
      "\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\sessions.py\", line 643, in send\n",
      "\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\sessions.py\", line 543, in get\n",
      "    return self.request('GET', url, **kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\sessions.py\", line 530, in request\n",
      "df = url_to_df(url=url,\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\history.py\", line 151, in url_to_df\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\sessions.py\", line 643, in send\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\sessions.py\", line 643, in send\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\sessions.py\", line 643, in send\n",
      "            return self.session.get(url, params=kwargs, proxies = self.proxy )resp = url(**params)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\nsepy\\commons.py\", line 167, in __call__\n",
      "r = adapter.send(request, **kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\adapters.py\", line 498, in send\n",
      "\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\sessions.py\", line 543, in get\n",
      "        return self.request('GET', url, **kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\sessions.py\", line 530, in request\n",
      "    return self.request('GET', url, **kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\sessions.py\", line 530, in request\n",
      "    r = adapter.send(request, **kwargs)\n",
      "raise ConnectionError(err, request=request)\n",
      "requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "        return self.session.get(url, params=kwargs, proxies = self.proxy )\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\sessions.py\", line 543, in get\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\adapters.py\", line 498, in send\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\adapters.py\", line 498, in send\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\sessions.py\", line 643, in send\n",
      "resp = self.send(prep, **send_kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\sessions.py\", line 643, in send\n",
      "            raise ConnectionError(err, request=request)\n",
      "requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n",
      "return self.request('GET', url, **kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\sessions.py\", line 530, in request\n",
      "r = adapter.send(request, **kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\adapters.py\", line 498, in send\n",
      "    return self.request('GET', url, **kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\sessions.py\", line 530, in request\n",
      "        raise ConnectionError(err, request=request)\n",
      "requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n",
      "resp = self.send(prep, **send_kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\sessions.py\", line 643, in send\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\sessions.py\", line 643, in send\n",
      "            raise ConnectionError(err, request=request)\n",
      "requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n",
      "    r = adapter.send(request, **kwargs)    r = adapter.send(request, **kwargs)    r = adapter.send(request, **kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\adapters.py\", line 498, in send\n",
      "\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\adapters.py\", line 498, in send\n",
      "\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\adapters.py\", line 498, in send\n",
      "raise ConnectionError(err, request=request)\n",
      "requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n",
      "resp = self.send(prep, **send_kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\sessions.py\", line 643, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\adapters.py\", line 498, in send\n",
      "    raise ConnectionError(err, request=request)\n",
      "requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n",
      "        r = adapter.send(request, **kwargs)\n",
      "  File \"c:\\users\\pratik garai\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\adapters.py\", line 498, in send\n",
      "    raise ConnectionError(err, request=request)\n",
      "requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n",
      "    raise ConnectionError(err, request=request)\n",
      "requests.exceptions.raise ConnectionError(err, request=request)\n",
      "requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n",
      "ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n",
      "    raise ConnectionError(err, request=request)\n",
      "requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n"
     ]
    }
   ],
   "source": [
    "def trainer():\n",
    "    start_pre = dt.datetime(2014,1,1)\n",
    "    end_pre = dt.datetime(2019,6,1)\n",
    "    stk_data_pre = gh(symbol=stock_,start=start_pre,end=end_pre)\n",
    "    pre_lim = 1335\n",
    "    reg1 = get_regressor(stk_data_pre, start_pre, end_pre, pre_lim)\n",
    "    \n",
    "    start_post = dt.datetime(2014,1,1)\n",
    "    end_post = dt.datetime(2020,8,1)\n",
    "    stk_data_post = gh(symbol=stock_,start=start_post,end=end_post)\n",
    "    post_lim = 1623\n",
    "    reg2 = get_regressor(stk_data_post, start_post, end_post, post_lim)\n",
    "    \n",
    "    comparison(start_post,end_post, post_lim, reg2, \"Corona trained on full\")\n",
    "    comparison(start_post,end_post, post_lim, reg1, \"Corona untrained on full\")\n",
    "    comparison()\n",
    "trainer()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
